name: build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Perform unittest
      run: |
        python test_project_euler.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git diff-index --quiet HEAD ||  git commit -m "Made changes (if any)" -a
        git push origin staging
